### ISSUE TITLE
Bug ao adicionar convidado a lista

### ISSUE THREAD

**Issue by ricardo-faria** [univas/guest-list-exam#1]
Ao adicionar um convidado a lista não esta aparecendo o nome, email e foto no painel.
Apenas ao recarregar a pagina os dados são carregados corretamente.

Este problema pode ser corrigido fazendo  "JSON.parse"  no dado vindo do servidor, como foi feito em meu repositório :
 https://github.com/ricardo-faria/guest-list-exam/blob/master/assets/js/GuestService.js#L13

**Comment by edysegura** [comment]
Olá Ricardo!

Por algum motivo a sua resposta do backend não está sendo parseada automaticamente. Veja este [exemplo](https://php-basics-edysegura.c9.io/php-restful/) sem o `JSON.parse`.

**Comment by edysegura** [comment]
Investigando um pouco mais sobre essa issue, o que aconteceu na verdade foi a ausência do código abaixo na sua API para informar ao jQuery que o conteúdo é um JSON e não um texto.

``` php
$app->response()->header('Content-Type', 'application/json');
```

Abraços,
